language: node_js
node_js:
  - node
env:
  global:
    - CC_TEST_REPORTER_ID=b506808c7c18d71f72139b583724ed271f26b72d449853d55352663dd6286c0f

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - make lint

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
